### ISSUE TITLE
Coveralls command fails at after_success in Travis build

### ISSUE THREAD

**Issue by caffalaughrey** [forcedotcom/SalesforcePy#6]
## Background
As we can see in Travis builds [like this one](https://travis-ci.com/forcedotcom/SalesforcePy/jobs/151267161), the `coveralls` command fails, seemingly as the .coverage/.coveragerc files are not in the current working directory.

```bash
$ coveralls --data_file=.coverage --config_file=.coveragerc
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/coveralls", line 11, in <module>
    sys.exit(wear())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coveralls/__init__.py", line 87, in wear
    coverage = coveralls(data_file=args.data_file, config_file=args.config_file)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/control.py", line 149, in __init__
    concurrency=concurrency,
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/config.py", line 467, in read_coverage_config
    raise CoverageException("Couldn't read '%s' as a config file" % fname)
coverage.misc.CoverageException: Couldn't read '/home/travis/build/forcedotcom/SalesforcePy/.coveragerc' as a config file
```

## Reproducible scenario
1. Make sure the fork of SalesforcePy for your Github account is enabled in Travis.
2. Push a commit.
3. View the corresponding Travis job.

## Actual results
Coveralls command fails.

## Expected results
Coverage stats should be sent to coveralls.  They should then [be visible here](https://coveralls.io/github/forcedotcom/SalesforcePy).

## Suggested fix
Possibly to remove the flags altogether.

**Comment by caffalaughrey** [comment]
Fix in: https://github.com/forcedotcom/SalesforcePy/pull/14
